### ISSUE TITLE
Does kong-plugin-prometheus can be used before kong 0.14.0?

### ISSUE THREAD

**Issue by liyuntao** [Kong/kong-plugin-prometheus#1]
I'm trying to bundle/install the plugin to kong 0.13.1. 
Basiclly execute luarocks install then modify configs to enable plugin.

After restarting kong, there's an error occur as below.

```
nginx: [error] [lua] exporter.lua:20: new(): prometheus: ngx shared dict 'prometheus_metrics' not found
```

**Comment by liyuntao** [comment]
I found the answer by the way :)  

The conf_loader would finally add a line `lua_shared_dict prometheus_metrics 5m;` to file `nginx_kong.lua`. After modify the file, everything goes ok.

**Comment by rgfretes** [comment]
Hi, Could you expand on how did you fix the problem? I am facing the same issue.
