### ISSUE TITLE
Remove kong_process_events from Grafana dashboards

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong-plugin-prometheus#101]
It's supposed to be full, but this looks like a problem on the dashboard. No real reason to report on it since it's not something users should care about under normal conditions.

**Comment by fffonion** [comment]
@hbagdi I was working on the grafana dashboard, is this still an issue? I seems not find the `kong_process_events` in dashboard anymore.

**Comment by hbagdi** [comment]
@fffonion I'm not sure. The last thing on this front was that the dashboard plots *all* shared dicts, which includes `kong_process_events`.

**Comment by fffonion** [comment]
I see, i thought `kong_process_events` was a metric. I will include this in #129
