### ISSUE TITLE
How does Kong Report path in the matadata

### ISSUE THREAD

**Issue by fing999** [Kong/kong-plugin-prometheus#105]
kong:
kong_http_status{app="ingress-kong",code="200",instance="xxxx,job="kubernetes-pods",kubernetes_namespace="kong",kubernetes_pod_name="ingress-kong-5bccc9d644-jsnxs",pod_template_hash="5bccc9d644",replica="Test",route="xxxxx",service="xxxx"}

**Comment by hbagdi** [comment]
It does not.

**Comment by fing999** [comment]
I don't know what you mean

**Comment by hbagdi** [comment]
Kong doesn't report path in Prometheus metrics.
