### ISSUE TITLE
Prometheus Exporters Hub by this repository! Thanks! :)

### ISSUE THREAD

**Issue by ralfyang** [Kong/kong-plugin-prometheus#107]
We made some open-source and service for about of prometheus exporter to find easy & use via your repository. 
If you have and question or improvement request about this, feel free to make an issue ticket to here -> https://github.com/NexClipper/exporterhub.io

Thanks for contribution :)

https://exporterhub.io

**Comment by hbagdi** [comment]
Great, I was wondering about adding it myself to exporterhub.io. Thank you for taking care of this on our behalf. Appreciate the work and effort!

**Comment by ralfyang** [comment]
Sure, you can add a list to here by PR 👍 
* https://github.com/NexClipper/exporterhub.io/blob/master/api/exporter_list.csv
