### ISSUE TITLE
Not able to enable the plugin

### ISSUE THREAD

**Issue by ghost** [Kong/kong-plugin-prometheus#13]
Tried to enable the plugin using the command:
curl http://localhost:8001/plugins -d "name=prometheus"

But getting the error:
{"config":"ngx shared dict 'prometheus_metrics' not found"}

**Comment by hbagdi** [comment]
Hello @Srihari96,

Which version of Kong are you using?

**Comment by ghost** [comment]
I am using Kong of version 0.11.2.

**Comment by hbagdi** [comment]
Hello @Srihari96,

This plugin can be used for Kong versions >= 0.13.0. This is necessary because the plugin records metrics for routes and services only and not the deprecated API entity in Kong.

Please upgrade your Kong version if you wish to use this plugin.

Thanks!
