### ISSUE TITLE
Kong 12.3 (APIs) - Runtime Error

### ISSUE THREAD

**Issue by milaw** [Kong/kong-plugin-prometheus#22]
Hi, I'm using kong 12.3

Enable the plugin on specific API or make it global cause the same error:

'2018/10/11 10:53:05 [error] 53#0: *224525 lua entry thread aborted: runtime error: ...local/share/lua/5.1/kong/plugins/prometheus/exporter.lua:56: attempt to index field 'service' (a nil value)
stack traceback:
coroutine 0:
	...local/share/lua/5.1/kong/plugins/prometheus/exporter.lua: in function 'log'
	.../local/share/lua/5.1/kong/plugins/prometheus/handler.lua:16: in function <.../local/share/lua/5.1/kong/plugins/prometheus/handler.lua:11>, context: ngx.timer, client: 77.126.8.37, server: 0.0.0.0:443'

Can you please let me know if the plugin does not support API?
Thanks

**Comment by hbagdi** [comment]
This plugin doesn't support API entities and will not support them as they are deprecated in Kong.
I'll recommend you to upgrade to Kong 0.14.x.
