### ISSUE TITLE
Will this project support api-obj defination in the near future?

### ISSUE THREAD

**Issue by liyuntao** [Kong/kong-plugin-prometheus#3]
Since api-obj still not removed in kong's logic, and the mainstream dashboard project(Konga and kong-dashboard) do not support service/route right now, we still use api-obj style defination in Admin API.

Currently kong-plugin-prometheus fetch label value(service="") by `message.service.name` in log() function, thus lead to empty label value when using api-obj defination. 

I wonder whether we should make a compatible for api defination(if service empty, fetching `message.request.api.name` instead ?) or completely remove support for api defination(for clearer semanteme meaning which provided by service model)

**Comment by Tieske** [comment]
the API definition will be removed. It is already deprecated, and will be removed from a future version.
