### ISSUE TITLE
Can't add datasource from Kong /metrics in Grafana

### ISSUE THREAD

**Issue by Apohg** [Kong/kong-plugin-prometheus#31]
Hello,

I have a real problem with this plugin. When I active it, it works. I have datas on the url http://kong:8001/metrics.
My issue come just after, when I need to add the datasource in grafana. I can't add the datasource, I have always the same error.
I'm using server mode (anyway, browser mode doesn't work either when i use http://localhost:8001/metrics and I can access it though my browser). I tried to indicate in grafana http://kong:8001 or http://kong:8001/metrics but I can't add the datasource. My containers can ping each others without any issue and from my grafana container I can curl http://kong:8001/metrics without any problem.. is there something I'm doing wrong?

#### Environment :
Docker Version:           18.06.1-ce
Kong image : 0.14.1
Grafana image : 5.2.4

#### Errors
When I'm adding the datasource, grafana IHM display `HTTP Error Not Found`

The first time I'm saving datasource I get this error:
```bash
grafana_app.ts:71 warning rootScope onAppEvent called without localscope
:3000/api/datasources/proxy/1/api/v1/query?query=1%2B1&time=1544101379.319:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
If I try again, still using http://kong:8001 or http://kong:8001/metrics I have this error : 
```bash
angular.js:12759 GET http://localhost:3000/api/datasources/proxy/1/api/v1/query?query=1%2B1&time=1544100307.71 404 (Not Found)
(anonymous)	@	angular.js:12759
g	@	angular.js:12492
u	@	angular.js:12244
u	@	angular.js:17051
(anonymous)	@	angular.js:17095
$digest	@	angular.js:18233
(anonymous)	@	angular.js:18462
i	@	angular.js:6362
(anonymous)	@	angular.js:6642
setTimeout (async)		
l.defer	@	angular.js:6640
$evalAsync	@	angular.js:18460
(anonymous)	@	angular.js:16923
l	@	angular.js:17095
h	@	angular.js:17122
d	@	angular.js:17106
resolve	@	angular.js:17001
(anonymous)	@	datasource_srv.ts:99
Promise.then (async)		
t.loadDatasource	@	datasource_srv.ts:81
t.get	@	datasource_srv.ts:65
t.testDatasource	@	ds_edit_ctrl.ts:149
(anonymous)	@	ds_edit_ctrl.ts:192
u	@	angular.js:17051
(anonymous)	@	angular.js:17095
$digest	@	angular.js:18233
$apply	@	angular.js:18531
(anonymous)	@	angular.js:18832
i	@	angular.js:6362
(anonymous)	@	angular.js:6642
setTimeout (async)		
l.defer	@	angular.js:6640
x	@	angular.js:18831
$applyAsync	@	angular.js:18563
u	@	angular.js:12544
v	@	angular.js:12785
k.onload	@	angular.js:12702
load (async)		
(anonymous)	@	angular.js:12685
g	@	angular.js:12492
u	@	angular.js:12244
u	@	angular.js:17051
(anonymous)	@	angular.js:17095
$digest	@	angular.js:18233
$apply	@	angular.js:18531
(anonymous)	@	angular.js:18832
i	@	angular.js:6362
(anonymous)	@	angular.js:6642
setTimeout (async)		
l.defer	@	angular.js:6640
x	@	angular.js:18831
$applyAsync	@	angular.js:18563
u	@	angular.js:12544
v	@	angular.js:12785
k.onload	@	angular.js:12702
load (async)		
(anonymous)	@	angular.js:12685
g	@	angular.js:12492
u	@	angular.js:12244
u	@	angular.js:17051
(anonymous)	@	angular.js:17095
$digest	@	angular.js:18233
$apply	@	angular.js:18531
(anonymous)	@	angular.js:27346
dispatch	@	jquery.js:5183
g.handle	@	jquery.js:4991
```

If anyone can explain me, maybe there is something I'm doing wrong.
I'm not sure if it's a prometheus plugin issue or grafana issue, but I guess people here know how configure grafana for use datasource from this plugin?
Thank you for reading :)

**Comment by hbagdi** [comment]
Hi @Apohg,

The plugin exposes metrics collected by Kong in [Prometheus Exposition Format](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md). You will need to run an instance of Prometheus in your cluster and then configure it to scrape this endpoint.

Once you've that working, you should be able to configure Grafana to use your Prometheus instance as your data source and see the metrics collected by Kong in Grafana.

There is a ready made [Grafana Dashboard](https://grafana.com/dashboards/7424) which you can use to visualize metrics exported by this plugin.
