### ISSUE TITLE
feature request: consumer_id added to all metrics

### ISSUE THREAD

**Issue by dcherniv** [Kong/kong-plugin-prometheus#36]
Hello,

It would be nice to have the ability to aggregate the response codes, request rates and such by consumer_id.

Like implemented here:
https://github.com/nijikokun/kong-plugin-prometheus/blob/master/kong/plugins/prometheus/handler.lua#L91

Thanks

**Comment by hbagdi** [comment]
This feature has come up in discussions before (see https://github.com/Kong/kong-plugin-prometheus/issues/20#issuecomment-427916656)

The main concern with this feature is cardinality of the data. Even with a few hundred or thousands of consumers, the number of time-series to keep in memory and during a scrape can get extremely large, resulting in very high memory utilization by Kong.
We usually recommend to use this Plugin for monitoring and observability and not for metrics per consumer.

**Comment by dcherniv** [comment]
@hbagdi Thank you for the response.
