### ISSUE TITLE
Per route metrics

### ISSUE THREAD

**Issue by trustlix** [Kong/kong-plugin-prometheus#40]
Is it possible to get per route metrics? The aggregated metrics per service are valuable, but would be great to be able to drilldown per route.

**Comment by hbagdi** [comment]
This is a feature that has been requested a few times.
While it is possible to track it, the problem arises with cardinality, where the number of time series can grow extremely large.

Let's keep this issue open and the community can pitch in ideas on how to make this efficient.


@trustlix Prometheus is usually used for monitoring purposes, and I assume you're using the service level metrics to track errors and various latency but would like to drill down via route to understand which endpoints in your application are slower than others or may be affect more than others? I'd like to know more details about your use-case to better understand the problem such a feature solves. Thank you!

**Comment by trustlix** [comment]
> This is a feature that has been requested a few times.
> While it is possible to track it, the problem arises with cardinality, where the number of time series can grow extremely large.
> 
> Let's keep this issue open and the community can pitch in ideas on how to make this efficient.
> 

Yeah, totally agree on the cardinality point you brought up.

> @trustlix Prometheus is usually used for monitoring purposes, and I assume you're using the service level metrics to track errors and various latency but would like to drill down via route to understand which endpoints in your application are slower than others or may be affect more than others? I'd like to know more details about your use-case to better understand the problem such a feature solves. Thank you!

That's indeed our scenario. Since detailed information on each route is very important for us, we are configuring Kong in a way that every service has only one route. Very troublesome but kind of works... So, in a sense, we are already paying the price for the cardinality problem you described above... we just can't operate our GW without such detailed per route metrics.

Would love to hear from other folks how they are handling this kind of requirement ... maybe there's some other plugin/tool that could be used for getting such metrics?

**Comment by huhu-sky** [comment]
We do have the same situation for per route metrics.

**Comment by huhu-sky** [comment]
@dliberman  thanks for your pr, If i want debug your new feature localhost, how could i do ?  i don't know how to debug kong plugin debug and how to build kong docker image? Is there a guid doc or website , thanks. @hbagdi

**Comment by hbagdi** [comment]
#48 was merged in manually. Stay tuned for the next release of this plugin and Kong.
