### ISSUE TITLE
Missing nginx state metrics

### ISSUE THREAD

**Issue by flowdopip** [Kong/kong-plugin-prometheus#50]
Hi,

I´ve launch my Kong Cluster in production and after setups the Oficial Kong Dashboard for metrics i found that some states of nginx is missing

# HELP kong_nginx_http_current_connections Number of HTTP connections
# TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="active"} 6
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="waiting"} 4
kong_nginx_http_current_connections{state="writing"} 2

state = total and handled are missing

Any reason?

Kong 1.1.2

Thanks

**Comment by hbagdi** [comment]
@flowdopip Are you using a custom server template to serve the `/metrics` endpoint or is this output from Kong's Admin port?

**Comment by flowdopip** [comment]
Yes, 
I'm using a custom template. But i already compare with the default one and is equals. The only thing changed was the access logs format to json.

**Comment by flowdopip** [comment]
Very strange. 
I have this nginx HTTP include directive for Prometheus metrics, only to have endpoint convention. This could be something to change in the plugin to everyone to choose the best endpoint path on the configuration

server {
     server_name kong_prometheus_exporter;
     listen 0.0.0.0:9542; # can be any other port as well

    location /monitoring/metrics {
        default_type text/plain;
        content_by_lua_block {
            local promethus = require "kong.plugins.prometheus.exporter"
            promethus:collect()
        }
    }

    location /monitoring/nginx {         
         access_log off;
         stub_status;
    }

    location /monitoring/ping {         
        return 200;
    }
    
    location /gc {
        content_by_lua_block {
            ngx.say(string.format("kong_nginx_worker_size{worker=%d} %.3f", ngx.var.pid, collectgarbage("count")))
        }
      }
}

On my Kong instance I'm able to do this:

ITERATION 1:

## http://localhost:9542/monitoring/metrics
- HELP kong_nginx_http_current_connections Number of HTTP connections
- TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="accepted"} 239
kong_nginx_http_current_connections{state="active"} 4
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="waiting"} 3
kong_nginx_http_current_connections{state="writing"} 1

ITERATION 2:

## http://localhost:8001/metrics
-- HELP kong_nginx_http_current_connections Number of HTTP connections
-- TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="accepted"} 239
kong_nginx_http_current_connections{state="active"} 4
kong_nginx_http_current_connections{state="handled"} 239
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="total"} 265
kong_nginx_http_current_connections{state="waiting"} 3
kong_nginx_http_current_connections{state="writing"} 1

ITERATION 3:
## http://localhost:9542/monitoring/metrics
-- HELP kong_nginx_http_current_connections Number of HTTP connections
-- TYPE kong_nginx_http_current_connections gauge
kong_nginx_http_current_connections{state="accepted"} 239
kong_nginx_http_current_connections{state="active"} 4
kong_nginx_http_current_connections{state="handled"} 239
kong_nginx_http_current_connections{state="reading"} 0
kong_nginx_http_current_connections{state="total"} 265
kong_nginx_http_current_connections{state="waiting"} 3
kong_nginx_http_current_connections{state="writing"} 1

for some reason after call the 8001/metrics the state="handled" and state="total" magically appear

Any idea?

**Comment by hbagdi** [comment]
You are missing in your custom Nginx template:
```
    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }
```

Once you add that, you will have access to the missing metrics as well.

**Comment by flowdopip** [comment]
No. I have it

**Comment by hbagdi** [comment]
@flowdopip Not sure what you mean. Is your problem resolved?

**Comment by flowdopip** [comment]
No, I follow your suggestion and check the code and I have this piece of code on the template. 
But the behavior is the same, not solved my problem
