### ISSUE TITLE
Kong Prometheus plugin  not passing metrics to Prometheus-operator. 

### ISSUE THREAD

**Issue by tpetrisk** [Kong/kong-plugin-prometheus#58]
I have Kong dist kubernetes 1.2-centos setup in a kubernetes cluster. One pod for kong-control-plane and another for kong-data-plane I am not unable to see any metrics be passed/collecteded in Prometheus-operator. Which is setup on the same kubernetes cluster. 

I also loaded  Grafana Dashboard as part of Prometheus-operator instalation via helm chart.
I am using the following dashboard: https://grafana.com/dashboards/7424 which states that Metrics collected via this plugin can be graphed in grafana

Below you will see I have 
    - Annotations for Prometheus 
    - include server config servers.conf 
    - set environment variable pointing to the server config KONG_NGINX_HTTP_INCLUDE=/kong/servers.conf

Setting on the kong-ingress-data-plane

    Annotations:    k8s.konghq.com/sidecar-inject: false
                    prometheus.io/port: 9542
                    prometheus.io/scrape: true
                
Prometheus metrics server from the container 

                
    [root@kong-ingress-data-plane-6c96454575-r2s5g /]# cat /kong/servers.conf 
    # Prometheus metrics server
    server {
        server_name kong_prometheus_exporter;
        listen 0.0.0.0:9542; # can be any other port as well
        access_log off;
        location /metrics {
            default_type text/plain;
            content_by_lua_block {
                 local prometheus = require "kong.plugins.prometheus.exporter"
                 prometheus:collect()
            }
        }
        location /nginx_status {
            internal;
            access_log off;
            stub_status;
        }
    }

Environment variable setting NGINX HTTP INCLUDE to servers.conf

    KONG_NGINX_HTTP_INCLUDE=/kong/servers.conf

    [root@kong-ingress-data-plane-6c96454575-r2s5g /]# echo $KONG_NGINX_HTTP_INCLUDE 
    /kong/servers.conf

listing plugins for services abtest 

    {
        "next": null,
        "data": [
            {
                "created_at": 1565048648,
                "config": {},
                "id": "06988bac-64a5-415e-ba9e-cd76732b8e70",
                "service": {
                    "id": "c63853a2-fde2-4df0-bf32-3b7be2cd5874"
                },
                "name": "prometheus",
                "protocols": [
                    "http",
                    "https"
                ],
                "enabled": true,
                "run_on": "first",
                "consumer": null,
                "route": null,
                "tags": null
            }
        ]
    }

Output when i so a get to retrieve metrics.

    https://{{kong-admin-url}}/metrics/

    # HELP kong_datastore_reachable Datastore reachable from Kong, 0 is unreachable
    # TYPE kong_datastore_reachable gauge
    kong_datastore_reachable 1
    # HELP kong_nginx_http_current_connections Number of HTTP connections
    # TYPE kong_nginx_http_current_connections gauge
    kong_nginx_http_current_connections{state="accepted"} 4216
    kong_nginx_http_current_connections{state="active"} 1
    kong_nginx_http_current_connections{state="handled"} 4216
    kong_nginx_http_current_connections{state="reading"} 0
    kong_nginx_http_current_connections{state="total"} 4238
    kong_nginx_http_current_connections{state="waiting"} 0
    kong_nginx_http_current_connections{state="writing"} 1
    # HELP kong_nginx_metric_errors_total Number of nginx-lua-prometheus errors
    # TYPE kong_nginx_metric_errors_total counter
    kong_nginx_metric_errors_total 0

Kong Namespace

    NAME                                           READY   STATUS    RESTARTS   AGE
    pod/kong-control-plane-7cfc458884-chnp4        1/1     Running   0          5h16m
    pod/kong-ingress-data-plane-6c96454575-r2s5g   1/1     Running   0          4h47m
    pod/postgres-66d4b459fb-8cgwb                  1/1     Running   0          2d22h

    NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
    service/kong-control-plane        NodePort    10.96.178.163   <none>        8001:32001/TCP,443:32444/TCP    2d22h
    service/kong-ingress-data-plane   NodePort    10.98.137.224   <none>        8000:32080/TCP,8443:32443/TCP   2d22h
    service/postgres                  ClusterIP   10.98.145.110   <none>        5432/TCP                        2d22h

    NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/kong-control-plane        1/1     1            1           5h16m
    deployment.apps/kong-ingress-data-plane   1/1     1            1           4h47m
    deployment.apps/postgres                  1/1     1            1           2d22h

    NAME                                                 DESIRED   CURRENT   READY   AGE
    replicaset.apps/kong-control-plane-7cfc458884        1         1         1       5h16m
    replicaset.apps/kong-ingress-data-plane-6c96454575   1         1         1       4h47m
    replicaset.apps/postgres-66d4b459fb                  1         1         1       2d22h

Prometheus-operator namespace

    NAME                                                         READY   STATUS    RESTARTS   AGE
    pod/alertmanager-prometheus-operator-alertmanager-0          2/2     Running   0          2d4h
    pod/prometheus-operator-grafana-9467d79ff-t8dt8              2/2     Running   0          2d4h
    pod/prometheus-operator-kube-state-metrics-57688466d-zqgnh   1/1     Running   0          2d4h
    pod/prometheus-operator-operator-5b697d85b7-r2dzf            2/2     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-2jkzl       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-2zh6k       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-4bgm2       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-9kqgh       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-dqmc8       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-s8phs       1/1     Running   0          2d4h
    pod/prometheus-operator-prometheus-node-exporter-tpvhd       1/1     Running   0          2d4h
    pod/prometheus-prometheus-operator-prometheus-0              3/3     Running   1          2d4h

    NAME                                                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                        AGE
    service/alertmanager-operated                          ClusterIP      None             <none>        9093/TCP,6783/TCP              2d4h
    service/prometheus-operated                            ClusterIP      None             <none>        9090/TCP                       2d4h
    service/prometheus-operator-alertmanager               NodePort       10.111.73.196    <none>        9093:30903/TCP                 2d4h
    service/prometheus-operator-grafana                    LoadBalancer   10.108.186.65    <pending>     80:31191/TCP                   2d4h
    service/prometheus-operator-kube-state-metrics         ClusterIP      10.99.2.63       <none>        8080/TCP                       2d4h
    service/prometheus-operator-operator                   LoadBalancer   10.110.16.87     <pending>     8080:32292/TCP,443:31058/TCP   2d4h
    service/prometheus-operator-prometheus                 NodePort       10.101.140.216   <none>        9090:30090/TCP                 2d4h
    service/prometheus-operator-prometheus-node-exporter   ClusterIP      10.104.90.134    <none>        9100/TCP                       2d4h

    NAME                                                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
    daemonset.apps/prometheus-operator-prometheus-node-exporter   7         7         7       7            7           <none>          2d4h

    NAME                                                     READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/prometheus-operator-grafana              1/1     1            1           2d4h
    deployment.apps/prometheus-operator-kube-state-metrics   1/1     1            1           2d4h
    deployment.apps/prometheus-operator-operator             1/1     1            1           2d4h

    NAME                                                               DESIRED   CURRENT   READY   AGE
    replicaset.apps/prometheus-operator-grafana-9467d79ff              1         1         1       2d4h
    replicaset.apps/prometheus-operator-kube-state-metrics-57688466d   1         1         1       2d4h
    replicaset.apps/prometheus-operator-operator-5b697d85b7            1         1         1       2d4h

    NAME                                                             READY   AGE
    statefulset.apps/alertmanager-prometheus-operator-alertmanager   1/1     2d4h
    statefulset.apps/prometheus-prometheus-operator-prometheus       1/1     2d4h

**Comment by hbagdi** [comment]
> I have Kong dist kubernetes 1.2-centos setup in a kubernetes cluster. One pod for kong-control-plane and another for kong-data-plane I am not unable to see any metrics be passed/collecteded in Prometheus-operator. Which is setup on the same kubernetes cluster.

Did you check if the metrics were collected in Prometheus?
It could be that the metrics are being collected by Prometheus but Grafana <-> Prometheus is having issues.

**Comment by tpetrisk** [comment]
I don't see anything in Prometheus/targets being collected by Prometheus. is there anything else i need to do to get prometheus to Scrape? I know i am missing something either on Kong or on Prometheus.

Thanks
Tim

**Comment by hbagdi** [comment]
> I don't see anything in Prometheus/targets being collected by Prometheus. is there anything else i need to do to get prometheus to Scrape? I know i am missing something either on Kong or on Prometheus.

This might have changed based on the Operator version but what you did [should be enough](https://konghq.com/blog/observability-kubernetes-kong/).
Do you have other pods in your cluster with the `prometheus.io/...` annotations that also have the same issue?

You might need to create a ServiceMonitor resource for Prometheus to scrape Kong's metrics.
Please see Prometheus docs for this purpose.

**Comment by hbagdi** [comment]
Please re-open if this is not resolved.

**Comment by IuriGarcia** [comment]
I would like to reopen that issue, since a similar problem is happening to me. 

steps to reproduce:

1 -install kong chart version 1.5.0 with the following values.ymal
```
kong:
  ingressController:
    enabled: true
    installCRDs: false
  proxy:
    type: LoadBalancer
    annotations:
      # nome dns para o kong proxy 
      external-dns.alpha.kubernetes.io/hostname: "url"
      #external-dns.alpha.kubernetes.io/ttl: 30
    http:
      enabled: true
    tls:
      enabled: false  
  admin:
    enabled: true
    http:
      enabled: false
    type: ClusterIP
    tls:
      enabled: true
  serviceMonitor:
    enabled: true    
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8444"

```
2 - install prometheus-operator like that
`helm install stable/prometheus-operator --generate-name -n abc`

if i do that installation with **stable/prometheus** chart, it works with http and https. although , with prometheus operator neither of those are working.

**Comment by hbagdi** [comment]
@rainest Can you help out here?

**Comment by rainest** [comment]
@IuriGarcia can you confirm that you're seeing the same scenario as the original report, where the `/metrics` endpoint is available and providing data? Are you able to see Kong metrics in the [expression browser](https://prometheus.io/docs/visualization/browser/)?

If not, do you see anything of interest in the Prometheus deployment's logs?

**Comment by IuriGarcia** [comment]
Hey guys, just solved that earlier.
@rainest yes, it was quite the same scenario.
SO, just looking up about prometheus-operator's ServiceMonitor, i have discovered that, in that case the Kong's  **ServiceMonitor.label** is needed.

Once i have deployed Prometheus-Operator it was necessary to describe prometheus crd created by that chart. and observe the mathLabel selector:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-frontend
  labels:
    prometheus: frontend
spec:
  version: v1.3.0
  # Define that all ServiceMonitor TPRs with the label `tier = frontend` should be included
  # into the server's configuration.
  serviceMonitors:
  - selector:
      matchLabels:
        tier: frontend
```

so, using that same label in Kongs **ServiceMonitor.label** and , deploying the KongPlugin as  demonstrated [here](https://konghq.com/blog/observability-kubernetes-kong/)
 i could deploy Kong and things start working with prometheus operator.

Ty so much @hbagdi and @rainest !
