### ISSUE TITLE
I got the metrics for Prometheus via port 9542，but js ERROR:ERR_CONTENT_LENGTH_MISMATCH 206

### ISSUE THREAD

**Issue by JoeHe0x** [Kong/kong-plugin-prometheus#59]
That's page before I added Prometheus
![image](https://user-images.githubusercontent.com/27885579/62748670-0a269800-ba8c-11e9-8895-12b0a7651425.png)
kubernetes kong
![image](https://user-images.githubusercontent.com/27885579/62748081-d64a7300-ba89-11e9-9c00-2a5a5b38882e.png)
this plugin has the capability to serve the content on a different port using a custom server block in Kong's NGINX template.
/path/to/prometheus-server.conf
server {
    server_name kong_prometheus_exporter;
    listen 0.0.0.0:9542;

    location / {
        default_type text/plain;
        content_by_lua_block {
             local prometheus = require "kong.plugins.prometheus.exporter"
             prometheus:collect()
        }
    }

    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }
}
![image](https://user-images.githubusercontent.com/27885579/62748296-bf585080-ba8a-11e9-925c-ebc169e3ab52.png)
And then there was an error on page
But the service via kong's route proxy is experiencing problems and the page is blank
js ERROR:ERR_CONTENT_LENGTH_MISMATCH 206
![image](https://user-images.githubusercontent.com/27885579/62747992-79e75380-ba89-11e9-856d-4daf979f6273.png)
![image](https://user-images.githubusercontent.com/27885579/62748017-9a171280-ba89-11e9-8679-7d26638af82d.png)

Then I delete the relevant configuration and it's OK
Why do I get metrics of Prometheus after following the operation, but it affects the service of kong proxy
@hbagdi

**Comment by JoeHe0x** [comment]
![image](https://user-images.githubusercontent.com/27885579/62749108-c5036580-ba8d-11e9-965e-b2d11c26e889.png)
Problem solved,I don't know why I added metrics of Prometheus, so there was that problem

**Comment by hbagdi** [comment]
From what I can understand, it seems like the problem was not with the Prometheus plugin but Kong, where Kong had issues buffering the proxied Javascript content.
The `proxy_buffers` directive that you put in the custom nginx config is at the `http` level and not `server` block level, so all proxied requests will use lthe larger buffer-size.

I'm closing the issue as it doesn't relate to this plugin specifically and you have solved the problem as well it seems.
