### ISSUE TITLE
kong-plugin-prometheus Metrics Is random

### ISSUE THREAD

**Issue by JoeHe0x** [Kong/kong-plugin-prometheus#65]
![image](https://user-images.githubusercontent.com/27885579/65583472-dd81fd80-dfb1-11e9-92e8-5c6d405ccaf8.png)
Kong is deployed on kubernetes with three pods enabled
Kong on every pod scrapes data, But the actual Metrics are the sum of the three pods,
Every visit to http://{kong-proxy}:9542/metrics  is a random pod Metrics

**Comment by hbagdi** [comment]
Each pod maintains it's own metrics.
You shouldn't be reading metrics for Kong via a load balancer, as each request will be routed to a different pod.

You want to use Prometheus to aggregate this data and then consume it via Prometheus.
