### ISSUE TITLE
Way to add custom metrics

### ISSUE THREAD

**Issue by james-callahan** [Kong/kong-plugin-prometheus#73]
It would be nice for Kong plugins to be able to add custom metrics to the prometheus endpoint.

At the lowest technical level, this could be done by exposing the `prometheus` object from the "exporter" module.

**Comment by Elyahou** [comment]
IS there a way to interact with kong prometheus from go plugin ?

**Comment by hbagdi** [comment]
I don't think so. @javierguerragiraldez can confirm.

You could have another Prometheus server in the Go code you write and have metrics in there instead of this plugin.

**Comment by javierguerragiraldez** [comment]
right.  plugins are mostly designed to work independently.  we're adding a bit of customizability to the data returned by `kong.log.serialize()`, but it's mostly intended to simplify plugin code, not explicitly as an interaction channel.  for that, we'd need some naming standard or guidelines to be respected by most of the log plugins.  it is a common theme in several requests, so it's something that we're considering for a future release.
