### ISSUE TITLE
prometheus.lua no memory issue

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/kong-plugin-prometheus#75]
I see this no memory issue in log, but actually there are free memory in my machine.

2019/12/26 13:46:20 [error] 22#0: *278974972 [lua] prometheus.lua:360: log_error(): Error while setting 'latency_bucket{type="kong",service="my service",route="04af9237-abd5-4bd3-b039-73d5e91c2011",le="05000.0"}' to '1': '**no memory**' while logging request, client: xxx, server: kong, request: "GET /checkalive HTTP/1.0", upstream: "http://xxx/checkalive"

[appadmin@my machine ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7821        3702         117         412        4002        3351
Swap:             0           0           0

I have no idea why it happens.

**Comment by hbagdi** [comment]
Please increase the size of the shared dictionary using the following configuration option in the config file:
```
nginx_http_lua_shared_dict = prometheus_metrics 10m
```

Even though you have free memory on the system, the amount of memory that the plugin can consume is limited by the shared dictionary size.

**Comment by JoyZhang66** [comment]
@hbagdi I'll try this, thank you for your help.
