### ISSUE TITLE
Custom default label -> value to labels

### ISSUE THREAD

**Issue by dmvieira** [Kong/kong-plugin-prometheus#83]
Do you know an option to export a static label -> value in all metrics?

**Comment by hbagdi** [comment]
You can use labeling in Prometheus to add static labels (during scrape) to all metrics that are scraped from Kong by Prometheus: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

**Comment by dmvieira** [comment]
Thx @hbagdi , I know that but it creates a dependency with how Prometheus is reading my metrics

**Comment by hbagdi** [comment]
That is the only way possible today.

> it creates a dependency with how Prometheus is reading my metrics

I don't understand the concern here. Could you please elaborate to help me understand the problem better?

**Comment by dmvieira** [comment]
I need to configure prometheus to rewrite labels just for my project. It's a dependency... I'm looking this code and it's really not supporting custom metrics. Do you think about support it?

**Comment by hbagdi** [comment]
My knowledge of Prometheus might be lacking but are there other exporters which do support this?
Is it a common pattern that is followed in the Prometheus community?

**Comment by hbagdi** [comment]
ping here

**Comment by dmvieira** [comment]
I really don't know about other exporters, but you can be the first one ;)

I'm already using relabel, but I think it's not the best practice because my server need to overwrite my configs.

I'll close this issue
