### ISSUE TITLE
new kong_up metric

### ISSUE THREAD

**Issue by ionutz22** [Kong/kong-plugin-prometheus#91]
Hi,

It would be nice if you can adjust the kong prometheus plugin to expose kong_up metric.

eg:
```
HELP kong_up Could the Kong server be reached
TYPE kong_up gauge

```
0 - if unreachable
1 - if reachable

This would be useful when using prometheus federation and relay on that building global dashboards in grafana.

Thank you.

**Comment by fffonion** [comment]
Is `datastore_reachable` the metrics you are looking for?

**Comment by ionutz22** [comment]
I might use that, but it's not clear to me if Kong is able to work without it's datastore. 
Most of exporters I've work with had the "exporter_up" metric which I could use to identify nodes exposing that service only and create dashboards and alerts based on that.

**Comment by hbagdi** [comment]
Please use the `up` metric that Prometheus generates for each target: https://prometheus.io/docs/concepts/jobs_instances/
