### ISSUE TITLE
Getting Internal Server Error(500) in /metrics endpoint in status listen

### ISSUE THREAD

**Issue by ghost** [Kong/kong-plugin-prometheus#93]
We are getting this error in prometheus plugin` [error] 31#0: *91 [lua] prometheus.lua:671: log_error(): counter not initialied while logging request`. We are using kong hybrid mode and only getting this error in kong data plane. It's intermittent. Some time we got metrics and some time it show internal server error(500) in /metrics endpoint.
We are using kong docker image in both plane.

**Comment by fffonion** [comment]
This is a bug in Kong, teleporting to https://github.com/Kong/kong/issues/6160

**Comment by ghost** [comment]
Ok thanks closing this one.
